name = "cloudflare-send-mail-custom-domain"
main = "src/index.js"
compatibility_date = "2022-05-14"
minify = true
type = "javascript"

[env.production]
workers_dev = false
zone_id = "53a91a9b8aa9808281a4735953dd7fd6"
route = "https://upskaler.com/"